#ImageDubstep Settings
#Tue Sep 23 05:59:35 EDT 2025
Bass\ Pitch\ (Hz)=80.0
Bass.Blue\ Threshold=0.3
Bass.Brightness\ Threshold=0.2
Bass.Duration\ (s)=0.5
Bass.Enable=true
Bass.Filter\ (Hz)=200.0
Bass.HalfPhase=0
Bass.LFO\ Depth\ (Hz)=200.0
Bass.LFO\ Rate\ (Hz)=2.0
Bass.Mid\ Blue\ Threshold=0.2
Bass.Mid\ Brightness\ Threshold=0.2
Bass.Rate=Normal
Bass.Resonance\ (Q)=10.0
Bass.Volume=0.5
Bass.WaveForm=Saw
BusHigh.Gain=1.0
BusHigh.HP=3500.0
BusHigh.LP=16000.0
BusLow.Gain=1.0
BusLow.HP=28.0
BusLow.LP=160.0
BusMid.Gain=1.0
BusMid.HP=140.0
BusMid.LP=4000.0
Corner\ Tau=0.8
FX.Ch.Depth=8.0
FX.Ch.Rate=0.6
FX.Ch.Wet=0.2
FX.Cr.Bits=10.0
FX.Cr.Down=2.0
FX.Cr.Wet=0.25
FX.Echo.Fb=0.35
FX.Echo.Time=280.0
FX.Echo.Wet=0.25
FX.Fl.Base=2.0
FX.Fl.Depth=1.2
FX.Fl.Fb=0.3
FX.Fl.Rate=0.25
FX.Fl.Wet=0.4
FX.Pan.Depth=0.5
FX.Pan.Rate=0.25
FX.Ph.Depth=0.9
FX.Ph.Fb=0.25
FX.Ph.Rate=0.3
FX.Ph.Stages=6.0
FX.Ph.Wet=0.35
FX.Rev.Damp=0.3
FX.Rev.Room=0.78
FX.Rev.Wet=0.2
FX.Tr.Depth=0.35
FX.Tr.Rate=4.0
FX.Wah.Max=2000.0
FX.Wah.Min=300.0
FX.Wah.Q=6.0
FX.Wah.Sens=1.0
FX.Wah.Wet=0.7
FX.Wide.Side=1.2
HiHat.Enable=true
HiHat.HP\ Filter\ (Hz)=8000.0
HiHat.Volume=0.3
HighFreq.Decay\ (s)=0.08
HighFreq.Detune\ (Hz)=0.0
HighFreq.Enable=true
HighFreq.HP\ Cutoff\ (Hz)=600.0
HighFreq.Osc\ Mix\ (saw\u2192square)=0.5
HighFreq.Volume=0.3
Kick.Attack\ (s)=0.2
Kick.Decay\ (s)=0.3
Kick.Enable=true
Kick.End\ Freq\ (Hz)=36.0
Kick.Energy\ Amp=0.3
Kick.Energy\ Threshold=0.3
Kick.HalfPhase=0
Kick.Punch\ /\ Drive=1.7
Kick.Rate=Normal
Kick.Red\ Amp=0.7
Kick.Red\ Threshold=0.4
Kick.Start\ Freq\ (Hz)=78.0
Kick.Tone\ Mix=0.25
Kick.Volume=0.8
Lim.Attack=1.0
Lim.Release=120.0
Lim.Thr=0.98
LinePerc.Decay\ (s)=0.12
LinePerc.Enable=true
LinePerc.Noise\ Blend=0.3
LinePerc.Resonance\ Q=5.0
LinePerc.Tone\ Freq\ Bias\ (Hz)=150.0
LinePerc.Tone\ Range\ (Hz)=300.0
LinePerc.Volume=0.4
Loop.Enable=true
Master\ Gain\ (dB)=100.0
MixHigh.Enable=true
MixLow.Enable=true
MixLow.Hat\ Trim=0.9
MixLow.High\ Layer\ Trim=1.0
MixLow.High\ Stagger\ (ms)=7.0
MixLow.Low\ Blend\ Trim=1.0
MixLow.Sub\ Duck\ (ms)=90.0
MixLow.Sub\ Nudge\ (ms)=18.0
Mono.Cut=120.0
Mono.Side=0.3
SC.Attack=3.0
SC.Depth=-6.0
SC.Ratio=3.0
SC.Release=120.0
SC.Threshold=0.02
Snare.Decay\ (s)=0.1
Snare.Enable=true
Snare.Filter\ (Hz)=300.0
Snare.Volume=0.6
Sub.Attack\ (ms)=8.0
Sub.Decay\ (s)=0.8
Sub.Drive=1.2
Sub.Enable=true
Sub.Frequency\ (Hz)=45.0
Sub.HalfPhase=0
Sub.Harmonic\ Mix=0.35
Sub.Rate=Normal
Sub.Stereo\ Width=0.0
Sub.Volume=0.9
Tempo\ (BPM)=140.0
View=RGB
Window\ Size\ (%)=50.0
Window\ X\ (%)=0.0
Window\ Y\ (%)=0.0
_format=imagedubstep.v1
